### ISSUE TITLE
Kobby plugin crashes on schemas with comments containing '%' symbols

### ISSUE THREAD

**Issue by ermadmi78** [ermadmi78/kobby#28]
```graphql
type Query {
    countries(offset: Int! = 0, limit: Int! = 100): [Country!]!
}

type Country {
    id: ID!
    """
    test %
    """
    name: String!

    films(offset: Int! = 0, limit: Int! = 100): [Film!]!
}

type Film {
    id: ID!
    title: String!

    country: Country!
}
```

Such a simple scheme gives an error:
```
Caused by: java.lang.IllegalArgumentException: dangling format characters in 'test %'
	at com.squareup.kotlinpoet.CodeBlock$Builder.add(CodeBlock.kt:284)
	at com.squareup.kotlinpoet.PropertySpec$Builder.addKdoc(PropertySpec.kt:190)
	at io.github.ermadmi78.kobby.generator.kotlin.DtoKt$generateDto$1$1$1$1$3$1$1$1.invoke(dto.kt:42)
	at io.github.ermadmi78.kobby.generator.kotlin.DtoKt$generateDto$1$1$1$1$3$1$1$1.invoke(dto.kt:41)
	at io.github.ermadmi78.kobby.model.KobbyField.comments(KobbyField.kt:236)
```

**Comment by ermadmi78** [comment]
Available since release 2.0.0-beta.01
