### ISSUE TITLE
java.lang.ClassFormatError for generated dto classes

### ISSUE THREAD

**Issue by nafania217518** [ermadmi78/kobby#43]
Hi everyone! 
We met following issue when amount of mutations in our schema reached value 246. 
kobby generates dto similar to following
```kotlin
data class MutationDto(
    val mutation1: String? = null,
    val mutation2: String? = null,
    val mutation3: String? = null,
    val mutation4: String? = null,
    val mutation5: String? = null,
    val mutation6: String? = null,
    val mutation7: String? = null,
    val mutation8: String? = null,
    val mutation9: String? = null,
    val mutation10: String? = null,
    val mutation11: String? = null,
    val mutation12: String? = null,
    val mutation13: String? = null,
    val mutation14: String? = null,
    val mutation15: String? = null,
    val mutation16: String? = null,
    val mutation17: String? = null,
    val mutation18: String? = null,
    val mutation19: String? = null,
    val mutation20: String? = null,
    val mutation21: String? = null,
    val mutation22: String? = null,
    val mutation23: String? = null,
    val mutation24: String? = null,
    val mutation25: String? = null,
    val mutation26: String? = null,
    val mutation27: String? = null,
    val mutation28: String? = null,
    val mutation29: String? = null,
    val mutation30: String? = null,
    val mutation31: String? = null,
    val mutation32: String? = null,
    val mutation33: String? = null,
    val mutation34: String? = null,
    val mutation35: String? = null,
    val mutation36: String? = null,
    val mutation37: String? = null,
    val mutation38: String? = null,
    val mutation39: String? = null,
    val mutation40: String? = null,
    val mutation41: String? = null,
    val mutation42: String? = null,
    val mutation43: String? = null,
    val mutation44: String? = null,
    val mutation45: String? = null,
    val mutation46: String? = null,
    val mutation47: String? = null,
    val mutation48: String? = null,
    val mutation49: String? = null,
    val mutation50: String? = null,
    val mutation51: String? = null,
    val mutation52: String? = null,
    val mutation53: String? = null,
    val mutation54: String? = null,
    val mutation55: String? = null,
    val mutation56: String? = null,
    val mutation57: String? = null,
    val mutation58: String? = null,
    val mutation59: String? = null,
    val mutation60: String? = null,
    val mutation61: String? = null,
    val mutation62: String? = null,
    val mutation63: String? = null,
    val mutation64: String? = null,
    val mutation65: String? = null,
    val mutation66: String? = null,
    val mutation67: String? = null,
    val mutation68: String? = null,
    val mutation69: String? = null,
    val mutation70: String? = null,
    val mutation71: String? = null,
    val mutation72: String? = null,
    val mutation73: String? = null,
    val mutation74: String? = null,
    val mutation75: String? = null,
    val mutation76: String? = null,
    val mutation77: String? = null,
    val mutation78: String? = null,
    val mutation79: String? = null,
    val mutation80: String? = null,
    val mutation81: String? = null,
    val mutation82: String? = null,
    val mutation83: String? = null,
    val mutation84: String? = null,
    val mutation85: String? = null,
    val mutation86: String? = null,
    val mutation87: String? = null,
    val mutation88: String? = null,
    val mutation89: String? = null,
    val mutation90: String? = null,
    val mutation91: String? = null,
    val mutation92: String? = null,
    val mutation93: String? = null,
    val mutation94: String? = null,
    val mutation95: String? = null,
    val mutation96: String? = null,
    val mutation97: String? = null,
    val mutation98: String? = null,
    val mutation99: String? = null,
    val mutation100: String? = null,
    val mutation101: String? = null,
    val mutation102: String? = null,
    val mutation103: String? = null,
    val mutation104: String? = null,
    val mutation105: String? = null,
    val mutation106: String? = null,
    val mutation107: String? = null,
    val mutation108: String? = null,
    val mutation109: String? = null,
    val mutation110: String? = null,
    val mutation111: String? = null,
    val mutation112: String? = null,
    val mutation113: String? = null,
    val mutation114: String? = null,
    val mutation115: String? = null,
    val mutation116: String? = null,
    val mutation117: String? = null,
    val mutation118: String? = null,
    val mutation119: String? = null,
    val mutation120: String? = null,
    val mutation121: String? = null,
    val mutation122: String? = null,
    val mutation123: String? = null,
    val mutation124: String? = null,
    val mutation125: String? = null,
    val mutation126: String? = null,
    val mutation127: String? = null,
    val mutation128: String? = null,
    val mutation129: String? = null,
    val mutation130: String? = null,
    val mutation131: String? = null,
    val mutation132: String? = null,
    val mutation133: String? = null,
    val mutation134: String? = null,
    val mutation135: String? = null,
    val mutation136: String? = null,
    val mutation137: String? = null,
    val mutation138: String? = null,
    val mutation139: String? = null,
    val mutation140: String? = null,
    val mutation141: String? = null,
    val mutation142: String? = null,
    val mutation143: String? = null,
    val mutation144: String? = null,
    val mutation145: String? = null,
    val mutation146: String? = null,
    val mutation147: String? = null,
    val mutation148: String? = null,
    val mutation149: String? = null,
    val mutation150: String? = null,
    val mutation151: String? = null,
    val mutation152: String? = null,
    val mutation153: String? = null,
    val mutation154: String? = null,
    val mutation155: String? = null,
    val mutation156: String? = null,
    val mutation157: String? = null,
    val mutation158: String? = null,
    val mutation159: String? = null,
    val mutation160: String? = null,
    val mutation161: String? = null,
    val mutation162: String? = null,
    val mutation163: String? = null,
    val mutation164: String? = null,
    val mutation165: String? = null,
    val mutation166: String? = null,
    val mutation167: String? = null,
    val mutation168: String? = null,
    val mutation169: String? = null,
    val mutation170: String? = null,
    val mutation171: String? = null,
    val mutation172: String? = null,
    val mutation173: String? = null,
    val mutation174: String? = null,
    val mutation175: String? = null,
    val mutation176: String? = null,
    val mutation177: String? = null,
    val mutation178: String? = null,
    val mutation179: String? = null,
    val mutation180: String? = null,
    val mutation181: String? = null,
    val mutation182: String? = null,
    val mutation183: String? = null,
    val mutation184: String? = null,
    val mutation185: String? = null,
    val mutation186: String? = null,
    val mutation187: String? = null,
    val mutation188: String? = null,
    val mutation189: String? = null,
    val mutation190: String? = null,
    val mutation191: String? = null,
    val mutation192: String? = null,
    val mutation193: String? = null,
    val mutation194: String? = null,
    val mutation195: String? = null,
    val mutation196: String? = null,
    val mutation197: String? = null,
    val mutation198: String? = null,
    val mutation199: String? = null,
    val mutation200: String? = null,
    val mutation201: String? = null,
    val mutation202: String? = null,
    val mutation203: String? = null,
    val mutation204: String? = null,
    val mutation205: String? = null,
    val mutation206: String? = null,
    val mutation207: String? = null,
    val mutation208: String? = null,
    val mutation209: String? = null,
    val mutation210: String? = null,
    val mutation211: String? = null,
    val mutation212: String? = null,
    val mutation213: String? = null,
    val mutation214: String? = null,
    val mutation215: String? = null,
    val mutation216: String? = null,
    val mutation217: String? = null,
    val mutation218: String? = null,
    val mutation219: String? = null,
    val mutation220: String? = null,
    val mutation221: String? = null,
    val mutation222: String? = null,
    val mutation223: String? = null,
    val mutation224: String? = null,
    val mutation225: String? = null,
    val mutation226: String? = null,
    val mutation227: String? = null,
    val mutation228: String? = null,
    val mutation229: String? = null,
    val mutation230: String? = null,
    val mutation231: String? = null,
    val mutation232: String? = null,
    val mutation233: String? = null,
    val mutation234: String? = null,
    val mutation235: String? = null,
    val mutation236: String? = null,
    val mutation237: String? = null,
    val mutation238: String? = null,
    val mutation239: String? = null,
    val mutation240: String? = null,
    val mutation241: String? = null,
    val mutation242: String? = null,
    val mutation243: String? = null,
    val mutation244: String? = null,
    val mutation245: String? = null,
    val mutation246: String? = null,
)
```
Which no longer can be instantiated since it has too many constructor properties. 
Error:
```
java.lang.ClassFormatError: Too many arguments in method signature in class file graphql/client/dto/MutationDto
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1023)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:862)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:760)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:681)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:639)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
```

I believe this also applies to any other generated dto with amount of properties >= 246

Any ideas how can we fix or workaround this issue without changes to graphql schema?

Thanks in advance

**Comment by nafania217518** [comment]
Hi, @ermadmi78

Thank you for quick reply!

Yes, it somehow allows to create this class, but it fails in runtime. Here is project to reproduce given issue:
https://github.com/nafania217518/generated_dto_issue

`TooManyArgumentsInDtoTest` will fail with this problem

Here is what we are using:
JVM: 22.0.1-temurin
Kotlin version: 2.0.0
Kobby version: 4.0.3
Gradle version: 8.8

**Comment by ermadmi78** [comment]
I think we can try to solve this problem by generating mutable DTO classes with empty constructors for GraphQL types with big amount of fields (>= 246). Our `MutationDto` should looks like:
```kotlin
class MutationDto {
    var mutation1: String? = null
    var mutation2: String? = null
    var mutation3: String? = null
    ...
    var mutation246: String? = null
}
```

DTO classes for GraphQL types with a small number of fields (< 246) should be generated as immutable data classes, as before.

**Comment by nafania217518** [comment]
Sounds good. Can't wait to test this out

**Comment by ermadmi78** [comment]
I will try to find time to fix this issue before the end of September.

**Comment by ermadmi78** [comment]
Hi, @nafania217518 

Could you please try [Kobby release 4.1.0-beta.01](https://github.com/ermadmi78/kobby/releases/tag/4.1.0-beta.01) on your test cases?

I supported generating mutable DTO and Input classes for GraphQL types with many fields. The threshold for the number of fields can be configured:

Gradle:
```kotlin
kobby {
    kotlin {
        dto {
            // Generate immutable DTO class if number of GraphQL type fields <= property value.
            // Otherwise, generate a mutable DTO class. Default value is 245.
            maxNumberOfFieldsForImmutableDtoClass = 245

            // Generate immutable Input class if number of GraphQL Input type fields <= property value.
            // Otherwise, generate a mutable Input class. Default value is 245.
            maxNumberOfFieldsForImmutableInputClass = 245
        }
    }
}
```
Maven:
```xml
<build>
    <plugins>
        <plugin>
            <groupId>io.github.ermadmi78</groupId>
            <artifactId>kobby-maven-plugin</artifactId>
            <executions>
                <execution>
                    <phase>generate-sources</phase>
                    <goals>
                        <goal>generate-kotlin</goal>
                    </goals>
                    <configuration>
                        <kotlin>
                            <dto>
                                <!-- Generate immutable DTO class if number of GraphQL type fields <= property value. -->
                                <!-- Otherwise, generate a mutable DTO class. Default value is 245. -->
                                <maxNumberOfFieldsForImmutableDtoClass>245</maxNumberOfFieldsForImmutableDtoClass>

                                <!--  Generate immutable Input class if number of GraphQL Input type fields <= property value. -->
                                <!-- Otherwise, generate a mutable Input class. Default value is 245. -->
                                <maxNumberOfFieldsForImmutableInputClass>245</maxNumberOfFieldsForImmutableInputClass>
                            </dto>
                        </kotlin>
                    </configuration>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
```

**Comment by ermadmi78** [comment]
Fixed in release 4.1.0
